/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2025-10-24T18:43:35.289Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Rick Roccasalva",
      photo: "https://scontent-sea5-1.cdninstagram.com/v/t51.2885-19/178494895_339655477510137_1129760596893548202_n.jpg?efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby45NTcuYzIifQ&_nc_ht=scontent-sea5-1.cdninstagram.com&_nc_cat=109&_nc_oc=Q6cZ2QGHV7iO1hGVFZTWbFU3d23iMRuO6DqCKHvZ8EJAjeDud9GAvXt8Bv6kRcAyto3lME4&_nc_ohc=DSdX86aEYFcQ7kNvwFcSm4j&_nc_gid=Ds4Rl_Ga_LMCQc6ym8FB2Q&edm=APoiHPcBAAAA&ccb=7-5&oh=00_AfcWBWRW0078MkgQa4ZN3nRIdFb_sLCFMCbRMMkSlHsF7w&oe=69007F55&_nc_sid=22de04",
      phone: "416 616 9369",
      email: "rick@istreetrealty.ca",
      company: "iStreet Realty Group - HomeLife Partners Realty Corp",
      license: "REALTOR®",
      repo: "New-Listing-186",
      companyAddress: "3850 Steeles Avenue W. Unit 6, Woodbridge, Ontario",
      companyLogo: "https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/KyeQTgnX03giMLGAsQCM/media/681d16a002d02015fb014c57.png"
    },
    social: {
      instagram: "https://www.instagram.com/istreetrealtygroup",
      facebook: "https://www.facebook.com/iStreetRealty",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: ""
    },
    email: "rroccasa1@gmail.com",
    phone: "(416) 555-0123",
    address: "3850 Steeles Avenue W. Unit 6, Woodbridge, Ontario",
    hours: "Mon-Fri: 9am-5pm",
    mapLocation: {
      lat: 43.7,
      lng: -79.4
    },
    socialLinks: {
      instagram: "https://www.instagram.com/homelifeintl/",
      facebook: "https://www.facebook.com/HomeLifeIntl",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: "https://linkedin.com/company/executivehomesrealtyinc"
    },
    agent2: {
      name: "Steven Simonetti",
      photo: "https://cdn.realtor.ca/individual/TS638851638600000000/highres/1053066.jpg",
      email: "steven@istreetrealty.ca",
      phone: "(416) 400-7653",
      company: "HomeLife Partners",
      license: "Broker of Record"
    }
  };

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117821674-Wallasey 1.png",
      alt: "Property image 1",
      category: "interior"
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822015-Wallasey 2.png",
      alt: "Property image 2",
      category: "kitchen"
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822166-Wallasey 3.png",
      alt: "Property image 3",
      category: "bedroom"
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822288-Wallasey 4.png",
      alt: "Property image 4",
      category: "bathroom"
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822423-Wallasey 5.png",
      alt: "Property image 5",
      category: "exterior"
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822565-Wallasey 6.png",
      alt: "Property image 6",
      category: "interior"
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822707-Wallasey 7.png",
      alt: "Property image 7",
      category: "kitchen"
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822849-Wallasey 8.png",
      alt: "Property image 8",
      category: "bedroom"
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822972-Wallasey 9.png",
      alt: "Property image 9",
      category: "bathroom"
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117823106-Wallasey 10.png",
      alt: "Property image 10",
      category: "exterior"
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117823222-Wallasey 11.png",
      alt: "Property image 11",
      category: "interior"
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117823409-Wallasey 12.png",
      alt: "Property image 12",
      category: "kitchen"
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117823540-Wallasey 13.png",
      alt: "Property image 13",
      category: "bedroom"
    }
  ];

// heroVideo configuration
export const heroVideo = {
    url: "https://mediatours.ca/property/55-wallasey-avenue-north-york/?access_token=27e8cbc52520b946c9e975e884cf94dc",
    type: "video/mp4",
    autoplay: true,
    loop: true,
    muted: true,
    playsInline: true
  };

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "4 Bedrooms",
      description: "Grand Entrance Double closets at the front entrance Expansive kitchen",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117821674-Wallasey 1.png"
    },
    {
      id: "section2",
      title: "4 Bathrooms",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822015-Wallasey 2.png"
    },
    {
      id: "section3",
      title: "3768 SqFt",
      description: "Spacious living area with ample room for your lifestyle",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822166-Wallasey 3.png"
    },
    {
      id: "section4",
      title: "$$2,285,000",
      description: "Den on the main floor",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117822288-Wallasey 4.png"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Humberlea-Pelmo Park W5",
    city: "Toronto",
    description: "Humberlea–Pelmo Park W5 is a family-oriented North York neighbourhood offering easy access to parks, schools and outdoor trails. Residents benefit from strong transit connections (including Weston GO and the upcoming Finch West LRT) and convenient shopping options such as Yorkdale Mall and local Superstore.",
    highlights: [
      "Close proximity to multiple schools and family services, including St. Simon Catholic School",
      "Direct access to Humber Trail and several riverside parks for walking and cycling",
      "Easy commuting via Weston GO, nearby TTC routes and future Finch West LRT connections",
      "Nearby shopping at Yorkdale Mall and large grocery options like Superstore",
      "Quick regional access via Hwy 401 and Hwy 400 for drivers"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Yorkdale Mall",
      distance: "",
      category: "shopping",
      iconName: "ShoppingBag"
    },
    {
      id: 2,
      name: "Acacia Park",
      distance: "",
      category: "recreation",
      iconName: "Leaf"
    },
    {
      id: 3,
      name: "St. Simon Catholic School (0.2 km)",
      distance: "0.2 km",
      category: "education",
      iconName: "School"
    },
    {
      id: 4,
      name: "Mr.Kane Juice Bar Toronto",
      distance: "",
      category: "dining",
      iconName: "Coffee"
    },
    {
      id: 5,
      name: "P&M Restaurant",
      distance: "",
      category: "dining",
      iconName: "Utensils"
    },
    {
      id: 6,
      name: "Weston Rd at Wallasey Ave (Bus Stop)",
      distance: "",
      category: "transportation",
      iconName: "Car"
    },
    {
      id: 7,
      name: "Wincott Wetland",
      distance: "",
      category: "recreation",
      iconName: "Users"
    },
    {
      id: 8,
      name: "Toronto Transit Commission - Arrow Road Garage",
      distance: "",
      category: "business",
      iconName: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "63/100",
      caption: "Somewhat Walkable",
      iconName: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "64/100",
      caption: "Good Transit",
      iconName: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "44/100",
      caption: "Somewhat Bikeable",
      iconName: "Compass",
      color: "bg-indigo-500"
    }
  ];

// openHouseBenefits configuration
export const openHouseBenefits = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 4 bedroom, 4 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Toronto.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "Backs on to a school with full privacy",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    nextDate: "October 24-25, 2025",
    time: "2:00 PM - 4:00 PM",
    host: "Rick R",
    phone: "416 616 9369",
    email: "rroccasa1@gmail.com",
    ctaText: "RSVP for Open House",
    virtualTourAvailable: false,
    virtualTourUrl: "",
    allOpenHouses: [
      {
        date: "Saturday, October 24, 2025",
        time: "2:00 PM - 4:00 PM"
      },
      {
        date: "Sunday, October 25, 2025",
        time: "2:00 PM - 4:00 PM"
      }
    ],
    date: "October 24-25, 2025",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "55 Wallasey Ave",
    registerLink: "https://55wallasey.com/openhouse"
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 4 bedroom, 4 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Toronto.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "Backs on to a school with full privacy",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// property configuration
export const property = {
    name: "55 Wallasey Ave",
    address: {
      street: "55 Wallasey Ave",
      city: "Toronto",
      state: "Ontario",
      zip: "M9M 1E1",
      country: "Canada"
    },
    price: "$2,285,000",
    beds: 4,
    baths: 4,
    sqft: 3768,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    type: "Detached",
    status: "For Sale",
    description: "Huge Lot - 77ft x 166 ft\nCustom solid oak floating circular staircase\nFinished basement with additional kitchen for multigenerational living",
    shortDescription: "4 BEDS + 4 BATHS in Toronto",
    longDescription: "Custom Built Home 3-Car Garage, 9 Car parking Huge 77ft X 166 ft Lot Finished Basement Separate entrance for Basement and Service Stairs",
    mainFeatures: [],
    propertyType: "Detached",
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117821674-Wallasey 1.png",
    heroCaption: "Custom Built + 3-Car Garage + Huge Lot = Your Perfect Family Home Just Listed!"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    "Custom built for existing owner, first time on the market, no wasted space",
    "200 amp service",
    "Den on the main floor",
    "Massive 77ft x 166 ft lot pool size lot, unique to the area",
    "Custom Built large Home at 3,768 sq ft",
    "3-Car Garage"
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/KyeQTgnX03giMLGAsQCM/media/681d16a002d02015fb014c57.png",
    logoAlt: "55 Wallasey Ave",
    favicon: "/favicon.ico",
    colors: {
      primary: "#D9A566",
      primaryDark: "#8B6839",
      primaryLight: "#E6C38C",
      dark: "#111111",
      light: "#FFFFFF"
    },
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117821674-Wallasey 1.png",
    footer: {
      copyrightText: "© 2024 55 Wallasey Ave. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change."
    },
    companyName: "HomeLife Partners",
    companyLogo: "https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/KyeQTgnX03giMLGAsQCM/media/681d16a002d02015fb014c57.png",
    accentColor: "#D9A566",
    footerText: "© 2024 55 Wallasey Ave. All rights reserved."
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "55 Wallasey Ave | Detached | Toronto",
    description: "Custom Built + 3-Car Garage + Huge Lot = Your Perfect Family Home Just Listed!",
    keywords: "detached, Toronto real estate, 4 bedroom, 4 bathroom, $2,285,000",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760117821674-Wallasey 1.png",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://55wallaseyave.com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Rick R provided exceptional service and found us exactly what we were looking for in Toronto.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Rick R presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Rick R knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg"
    }
  ];

